name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # 🔹 Authenticate with Azure (Fixed)
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 🔹 Login to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: az acr login --name mycontainerregistry

      # 🔹 Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t mycontainerregistry.azurecr.io/flask-app:${{ github.sha }} .
          docker push mycontainerregistry.azurecr.io/flask-app:${{ github.sha }}

      # 🔹 Get AKS Credentials
      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group MyResourceGroup --name MyAKSCluster

      # 🔹 Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/flask-app flask-app=mycontainerregistry.azurecr.io/flask-app:${{ github.sha }}
          kubectl rollout status deployment/flask-app
