name: Deploy to AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # ✅ Needed for GitHub Actions to authenticate with Azure

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 🔹 Log in to Azure using OpenID Connect (OIDC)
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 🔹 Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: az acr login --name mycontainerregistry

      # 🔹 Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t mycontainerregistry.azurecr.io/flask-app:${{ github.sha }} .
          docker push mycontainerregistry.azurecr.io/flask-app:${{ github.sha }}

      # 🔹 Get AKS Credentials
      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group MyResourceGroup --name MyAKSCluster

      # 🔹 Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/flask-app flask-app=mycontainerregistry.azurecr.io/flask-app:${{ github.sha }}
          kubectl rollout status deployment/flask-app
