name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ✅ Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # ✅ Log in to Azure securely using GitHub Secrets
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # ✅ Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # ✅ Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:${{ github.sha }} .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/flask-app:${{ github.sha }}

      # ✅ Get AKS Credentials
      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      # ✅ Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/flask-app flask-app=${{ secrets.ACR_NAME }}.azurecr.io/flask-app:${{ github.sha }}
          kubectl rollout status deployment/flask-app
