name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Runs deployment on every push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: IDENTITY  # OIDC Login

      - name: Verify Azure Login
        run: az account show

      - name: Build and Push Docker Image
        run: |
          docker build -t my-flask-app .
          echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login myregistry.azurecr.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
          docker tag my-flask-app myregistry.azurecr.io/my-flask-app:latest
          docker push myregistry.azurecr.io/my-flask-app:latest

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name myregistry.azurecr.io/my-flask-app:latest \
            --docker-registry-server-url https://myregistry.azurecr.io \
            --docker-registry-server-user ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} \
            --docker-registry-server-password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Restart Azure Web App
        run: az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
