name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # 🔹 Authenticate with Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 🔹 Login to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: az acr login --name MyContainerRegistry

      # 🔹 Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t mycontainerregistry.azurecr.io/myapp:${{ github.sha }} .
          docker push mycontainerregistry.azurecr.io/myapp:${{ github.sha }}

      # 🔹 Get AKS Credentials
      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group MyResourceGroup --name MyAKSCluster

      # 🔹 Deploy to AKS
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/myapp myapp=mycontainerregistry.azurecr.io/myapp:${{ github.sha }}
          kubectl rollout status deployment/myapp

